name: Testing
on: push

jobs:
  test_projects: 
    runs-on: windows
    steps:
    - uses: actions/checkout@v3
    - name: Run Django unit tests
      run: |
        pip install --user django
        python3 manage.py test
